server:
  port: 8771
spring:
  application:
    name: yuan-cam-eureka2
eureka:
  instance:
    #eureka实例主机名
    hostname: 127.0.0.1
  client:
    #把自己注册到eureka上面
    register-with-eureka: true
    #从eureka上获取服务
    fetch-registry: true
    #注册中心地址
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/